# Generated by Django 4.2 on 2024-01-29 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TodoAPI", "0004_remove_todo_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="user",
        ),
    ]
